### ISSUE TITLE
Не работает Anilibria 

### ISSUE THREAD

**Issue by xboxones1** [Eviloid/kodi.repository#5]
Здравствуйте. 
На днях перестало работать. 
При открытии плагина сразу ошибка. 
В лог пишет это:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.evld.anilibria.tv/default.py", line 436, in <module>
main_menu()
File "/storage/.kodi/addons/plugin.video.evld.anilibria.tv/default.py", line 73, in main_menu
html = get_html(BASE_URL)
File "/storage/.kodi/addons/plugin.video.evld.anilibria.tv/default.py", line 42, in get_html
conn = urllib2.urlopen(request)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
File "/usr/lib/python2.7/urllib2.py", line 435, in open
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
File "/usr/lib/python2.7/urllib2.py", line 473, in error
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 403: Forbidden
-->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.evld.anilibria.tv/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.evld.anilibria.tv/) failed
```

**Comment by Eviloid** [comment]
_HTTPError: HTTP Error 403: Forbidden_

это возможно Cloudflare DDOS protection
попробуйте через браузер на сайт анилибрии зайти

**Comment by xboxones1** [comment]
Действительно, стало редиректить на cloudflare. Буквально на днях все работало.
